import math
from popcount import *

def generate_group_sum(rtl_path, module_name, lut_num, class_num):
    """
    Generate Verilog code for a group sum module.
    Parameters:
        rtl_path (str): Path to the RTL directory.
        module_name (str): Name of the module.
        lut_num (int): Number of LUT entries.
        class_num (int): Number of classes.
    """
    rtl_code = []
    rtl_code.append("`timescale 1ns/1ps\n")
    rtl_code.append("module "+module_name+"(\n")
    rtl_code.append("    input  clk,\n")
    rtl_code.append("    input  rst_n,\n")
    rtl_code.append("    input  data_i_vld,\n")
    rtl_code.append("    input  ["+str(lut_num-1)+":0] data_i,\n")
    rtl_code.append("    output data_o_vld,\n")
    rtl_code.append("    output ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] data_o\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    data_num_per_class = lut_num//class_num
    rtl_code.append("\n")
    rtl_code.append("wire ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] sum_result_wire [0:"+str(class_num-1)+"];\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] sum_result_reg [0:"+str(class_num-1)+"];\n")
    rtl_code.append("\n")
    rtl_code.append("\n")

    for class_idx in range(class_num):
        rtl_code.append("popcount_bitnum_"+str(data_num_per_class)+" u_popcount_"+str(class_idx)+"(\n")
        rtl_code.append("    .data_i    (data_i["+str(class_idx+1)+"*"+str(data_num_per_class)+"-1:"+str(class_idx)+"*"+str(data_num_per_class)+"]),\n")
        rtl_code.append("    .data_o    (sum_result_wire["+str(class_idx)+"])\n")
        rtl_code.append(");\n")
        rtl_code.append("\n")
        generate_popcount(rtl_path, "popcount_bitnum_"+str(data_num_per_class), data_num_per_class)
        rtl_code.append("\n")
        rtl_code.append("always @(posedge clk or negedge rst_n)\n")
        rtl_code.append("begin\n")
        rtl_code.append("    if (!rst_n)\n")
        rtl_code.append("    begin\n")
        rtl_code.append("        sum_result_reg["+str(class_idx)+"] <= 0;\n")
        rtl_code.append("    end\n")
        rtl_code.append("    else if(data_i_vld)\n")
        rtl_code.append("    begin\n")
        rtl_code.append("        sum_result_reg["+str(class_idx)+"] <= sum_result_wire["+str(class_idx)+"];\n")
        rtl_code.append("    end\n")
        rtl_code.append("end\n")
    rtl_code.append("\n")
    rtl_code.append("reg data_i_vld_d_0;\n")
    rtl_code.append("reg data_i_vld_d_1;\n")
    rtl_code.append("always @(posedge clk or negedge rst_n)\n")
    rtl_code.append("begin\n")
    rtl_code.append("    if (!rst_n)\n")
    rtl_code.append("    begin\n")
    rtl_code.append("        data_i_vld_d_0 <= 1'b0;\n")
    rtl_code.append("        data_i_vld_d_1 <= 1'b0;\n")
    rtl_code.append("    end\n")
    rtl_code.append("    else\n")
    rtl_code.append("    begin\n")
    rtl_code.append("        data_i_vld_d_0 <= data_i_vld;\n")
    rtl_code.append("        data_i_vld_d_1 <= data_i_vld_d_0;\n")
    rtl_code.append("    end\n")
    rtl_code.append("end\n")
    rtl_code.append("\n")
    rtl_code.append("\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_0;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_0;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_1;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_1;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_2;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_2;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_3;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_3;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_0_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_0_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_1_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_1_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_2_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_2_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(class_num+1)))+"-1:0] max_class_3_reg;\n")
    rtl_code.append("reg ["+str(math.ceil(math.log2(data_num_per_class+1)))+"-1:0] max_value_3_reg;\n")
    rtl_code.append("integer i,j,m;\n")
    rtl_code.append("\n")
    rtl_code.append("always @(*) begin\n")
    rtl_code.append("    max_class_0 = 0;\n")
    rtl_code.append("    max_class_1 = 0;\n")
    rtl_code.append("    max_class_2 = 0;\n")
    rtl_code.append("    max_class_3 = 0;\n")
    rtl_code.append("    max_value_0 = sum_result_reg[0];\n")
    rtl_code.append("    max_value_1 = sum_result_reg["+str(class_num//3)+"];\n")
    rtl_code.append("    max_value_2 = sum_result_reg["+str((class_num//3)*2)+"];\n")
    rtl_code.append("    max_value_3 = sum_result_reg["+str((class_num//3)*3)+"];\n")
    rtl_code.append("    for (i = 0; i < "+str(class_num//3)+"; i = i + 1) begin\n")
    rtl_code.append("        if (sum_result_reg[i] > max_value_0) begin\n")
    rtl_code.append("            max_value_0 = sum_result_reg[i];\n")
    rtl_code.append("            max_class_0 = i["+str(math.ceil(math.log2(class_num+1)))+"-1:0];\n")
    rtl_code.append("        end\n")
    rtl_code.append("    end\n")
    rtl_code.append("    for (j = "+str(class_num//3)+"; j < "+str((class_num//3)*2)+"; j = j + 1) begin\n")
    rtl_code.append("        if (sum_result_reg[j] > max_value_1) begin\n")
    rtl_code.append("            max_value_1 = sum_result_reg[j];\n")
    rtl_code.append("            max_class_1 = j["+str(math.ceil(math.log2(class_num+1)))+"-1:0];\n")
    rtl_code.append("        end\n")
    rtl_code.append("    end\n")
    rtl_code.append("    for (m = "+str((class_num//3)*2)+"; m < "+str(class_num)+"; m = m + 1) begin\n")
    rtl_code.append("        if (sum_result_reg[m] > max_value_2) begin\n")
    rtl_code.append("            max_value_2 = sum_result_reg[m];\n")
    rtl_code.append("            max_class_2 = m["+str(math.ceil(math.log2(class_num+1)))+"-1:0];\n")
    rtl_code.append("        end\n")
    rtl_code.append("    end\n")
    rtl_code.append("    for (m = "+str((class_num//3)*3)+"; m < "+str(class_num)+"; m = m + 1) begin\n")
    rtl_code.append("        if (sum_result_reg[m] > max_value_3) begin\n")
    rtl_code.append("            max_value_3 = sum_result_reg[m];\n")
    rtl_code.append("            max_class_3 = m["+str(math.ceil(math.log2(class_num+1)))+"-1:0];\n")
    rtl_code.append("        end\n")
    rtl_code.append("    end\n")
    rtl_code.append("end\n")
    rtl_code.append("\n")
    rtl_code.append("always @(posedge clk or negedge rst_n)\n")
    rtl_code.append("begin\n")
    rtl_code.append("   if(rst_n==1'b0)\n")
    rtl_code.append("   begin\n")
    rtl_code.append("       max_value_0_reg     <=      "+str(math.ceil(math.log2(data_num_per_class+1)))+"'b0;\n")
    rtl_code.append("       max_value_1_reg     <=      "+str(math.ceil(math.log2(data_num_per_class+1)))+"'b0;\n")
    rtl_code.append("       max_value_2_reg     <=      "+str(math.ceil(math.log2(data_num_per_class+1)))+"'b0;\n")
    rtl_code.append("       max_value_3_reg     <=      "+str(math.ceil(math.log2(data_num_per_class+1)))+"'b0;\n")
    rtl_code.append("       max_class_0_reg     <=      "+str(math.ceil(math.log2(class_num+1)))+"'b0;\n")
    rtl_code.append("       max_class_1_reg     <=      "+str(math.ceil(math.log2(class_num+1)))+"'b0;\n")
    rtl_code.append("       max_class_2_reg     <=      "+str(math.ceil(math.log2(class_num+1)))+"'b0;\n")
    rtl_code.append("       max_class_3_reg     <=      "+str(math.ceil(math.log2(class_num+1)))+"'b0;\n")
    rtl_code.append("   end\n")
    rtl_code.append("   else\n")
    rtl_code.append("   begin\n")
    rtl_code.append("       max_value_0_reg     <=      max_value_0;\n")
    rtl_code.append("       max_value_1_reg     <=      max_value_1;\n")
    rtl_code.append("       max_value_2_reg     <=      max_value_2;\n")
    rtl_code.append("       max_value_3_reg     <=      max_value_3;\n")
    rtl_code.append("       max_class_0_reg     <=      max_class_0;\n")
    rtl_code.append("       max_class_1_reg     <=      max_class_1;\n")
    rtl_code.append("       max_class_2_reg     <=      max_class_2;\n")
    rtl_code.append("       max_class_3_reg     <=      max_class_3;\n")
    rtl_code.append("   end\n")
    rtl_code.append("end\n")
    rtl_code.append("\n")
    rtl_code.append("always @(posedge clk or negedge rst_n)\n")
    rtl_code.append("begin\n")
    rtl_code.append("   if(rst_n==1'b0)\n")
    rtl_code.append("   begin\n")
    rtl_code.append("       max_class       <=      "+str(math.ceil(math.log2(class_num)))+"'b0;\n")
    rtl_code.append("   end\n")
    rtl_code.append("   else\n")
    rtl_code.append("   begin\n")
    rtl_code.append("       if ((max_value_0_reg > max_value_1_reg) && (max_value_0_reg > max_value_2_reg) && (max_value_0_reg > max_value_3_reg)) begin\n")
    rtl_code.append("           max_class       <=      max_class_0_reg;\n")
    rtl_code.append("       end\n")
    rtl_code.append("       else if((max_value_1_reg > max_value_0_reg) && (max_value_1_reg > max_value_2_reg) && (max_value_1_reg > max_value_3_reg)) begin\n")
    rtl_code.append("           max_class       <=      max_class_1_reg;\n")
    rtl_code.append("       end\n")
    rtl_code.append("       else if((max_value_2_reg > max_value_0_reg) && (max_value_2_reg > max_value_1_reg) && (max_value_2_reg > max_value_3_reg)) begin\n")
    rtl_code.append("           max_class       <=      max_class_2_reg;\n")
    rtl_code.append("       end\n")
    rtl_code.append("       else begin\n")
    rtl_code.append("           max_class       <=      max_class_3_reg;\n")
    rtl_code.append("       end\n")
    rtl_code.append("   end\n")
    rtl_code.append("end\n")
    rtl_code.append("\n")
    rtl_code.append("reg data_o_vld_reg;\n")
    rtl_code.append("\n")
    rtl_code.append("always @(posedge clk or negedge rst_n) begin\n")
    rtl_code.append("    if (!rst_n) \n")
    rtl_code.append("    begin\n")
    rtl_code.append("        data_o_vld_reg <= 0;\n")
    rtl_code.append("    end \n")
    rtl_code.append("    else\n")
    rtl_code.append("    begin\n")
    rtl_code.append("        data_o_vld_reg <= data_i_vld_d_1;\n")
    rtl_code.append("    end\n")
    rtl_code.append("end\n")
    rtl_code.append("\n")
    rtl_code.append("assign data_o_vld = data_o_vld_reg;\n")
    rtl_code.append("assign data_o = max_class;\n")
    rtl_code.append("\n")
    rtl_code.append("endmodule\n")

    with open(rtl_path+"/"+module_name + ".v", "w") as f:
        for i in rtl_code:
            f.write(i)