def generate_popcount_2lut(rtl_path):
    rtl_code = []
    rtl_code.append("module popcount_2lut(\n")
    rtl_code.append("    input [2:0] bits,\n")
    rtl_code.append("    output [1:0] count\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("LUT6 #(\n")
    rtl_code.append("   .INIT(64'h0000000000000096)\n")
    rtl_code.append(") lut_0 (\n")
    rtl_code.append("   .O(count[0]),\n")
    rtl_code.append("   .I0(bits[0]),\n")
    rtl_code.append("   .I1(bits[1]),\n")
    rtl_code.append("   .I2(bits[2]),\n")
    rtl_code.append("   .I3(1'b0),\n")
    rtl_code.append("   .I4(1'b0),\n")
    rtl_code.append("   .I5(1'b0)\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("LUT6 #(\n")
    rtl_code.append("   .INIT(64'h00000000000000E8)\n")
    rtl_code.append(") lut_1 (\n")
    rtl_code.append("   .O(count[1]),\n")
    rtl_code.append("   .I0(bits[0]),\n")
    rtl_code.append("   .I1(bits[1]),\n")
    rtl_code.append("   .I2(bits[2]),\n")
    rtl_code.append("   .I3(1'b0),\n")
    rtl_code.append("   .I4(1'b0),\n")
    rtl_code.append("   .I5(1'b0)\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("endmodule\n")

    with open(rtl_path+"/popcount_2lut.v", "w") as f:
        for i in rtl_code:
            f.write(i)