def generate_popcount_3lut(rtl_path):
    rtl_code = []
    rtl_code.append("module popcount_3lut(\n")
    rtl_code.append("    input [5:0] bits,\n")
    rtl_code.append("    output [2:0] count\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("LUT6 #(\n")
    rtl_code.append("   .INIT(64'h6996966996696996)\n")
    rtl_code.append(") lut_0 (\n")
    rtl_code.append("   .O(count[0]),\n")
    rtl_code.append("   .I0(bits[0]),\n")
    rtl_code.append("   .I1(bits[1]),\n")
    rtl_code.append("   .I2(bits[2]),\n")
    rtl_code.append("   .I3(bits[3]),\n")
    rtl_code.append("   .I4(bits[4]),\n")
    rtl_code.append("   .I5(bits[5])\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("LUT6 #(\n")
    rtl_code.append("   .INIT(64'h8117177E177E7EE8)\n")
    rtl_code.append(") lut_1 (\n")
    rtl_code.append("   .O(count[1]),\n")
    rtl_code.append("   .I0(bits[0]),\n")
    rtl_code.append("   .I1(bits[1]),\n")
    rtl_code.append("   .I2(bits[2]),\n")
    rtl_code.append("   .I3(bits[3]),\n")
    rtl_code.append("   .I4(bits[4]),\n")
    rtl_code.append("   .I5(bits[5])\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("LUT6 #(\n")
    rtl_code.append("   .INIT(64'hFEE8E880E8808000)\n")
    rtl_code.append(") lut_2 (\n")
    rtl_code.append("   .O(count[2]),\n")
    rtl_code.append("   .I0(bits[0]),\n")
    rtl_code.append("   .I1(bits[1]),\n")
    rtl_code.append("   .I2(bits[2]),\n")
    rtl_code.append("   .I3(bits[3]),\n")
    rtl_code.append("   .I4(bits[4]),\n")
    rtl_code.append("   .I5(bits[5])\n")
    rtl_code.append(");\n")
    rtl_code.append("\n")
    rtl_code.append("endmodule\n")

    with open(rtl_path+"/popcount_3lut.v", "w") as f:
        for i in rtl_code:
            f.write(i)